Add customizable endpoint exclusion
ncasaux/camel-plantuml pull request #19
Opened 2024-10-25 16:59 UTC by ahauschulte

Camel-plantuml is a powerful tool for visualizing Camel routes, from small and simple routes to larger and more complex ones. In my use cases with complex routes, however, I found that certain endpoints were irrelevant to the specific diagrams I wanted to create, and their inclusion sometimes reduced clarity.

This PR introduces a new URL parameter (`uriFilterPattern`), allowing users to filter out specified endpoints in the PlantUML output, thereby better aligning the visual output to specific needs and enhancing readability for focused use cases. I’ve included two unit tests to demonstrate the parameter’s use.

2024-11-03 23:46 UTC, ncasaux commented
Thank you @ahauschulte for your interest in this project and for your suggestion! 
I could not find the unit tests you mentioned, or maybe I missed something ?

2024-11-04 06:33 UTC, ahauschulte commented
Thank you for pointing out that the tests were missing. I've updated the pull request.

2024-11-05 20:52 UTC, ncasaux requested changes
I think there is a small bug where I added a comment.
Anyway, you really perfectly integrated your feature into my code, congratulations ! 👍

2024-11-05 20:52 UTC, ncasaux commented on camel-plantuml-jar/src/main/java/io/github/ncasaux/camelplantuml/generator/RoutesDiagramGenerator.java
> +            if (parameters.uriFilterPattern().matcher(routeEndpointBaseUri).matches()) {
If we want to filter based on the route Id, I think we should not use the `routeEndpointBaseUri` but the `routeId` instead.

2024-11-07 20:11 UTC, ahauschulte commented
Thank you for the feedback and your kind words.

I reviewed the filter section in the `RoutesDiagramGenerator` class and think that filtering should indeed be based on the `routeEndPointBaseUri`. Filtering by `routeId` would not work as intended (the test in `DefaultExampleWithUriFilterPatternTest.java` would fail in that case and the generated diagram would be incorrect).

Perhaps the log statement within the `if` block was unclear? I’ve made an effort to clarify it.

2024-11-09 19:16 UTC, ncasaux commented
Your modification makes sense, as it's a URI filter, not an ID filter.
Thanks for adding the routeEndPointBaseUri in the log.

2024-11-09 19:21 UTC, merged

2024-11-09 20:09 UTC, ncasaux commented
I've published version 1.8.0, it should be available soon in Maven Central.
Thanks again for your PR! 👍

2024-11-10 07:48 UTC, ahauschulte commented
Thanks for merging the PR; and thank you for camel-plantuml, it's a very useful tool.